import type { Locale } from "./content";

// Every piece of UI copy that is not already in content.ts, in both languages.
// Pages read from here so one component renders both ans.digital and ans.bd.

const en = {
  brand: "ANS Digital",
  nav: { cta: "Contact sales", menu: "Menu", lang: "বাংলা" },
  hero: {
    kicker: "Music & media technology",
    title: "Reliable Music & Media Technology Solutions",
    lead1: "ANS Digital builds the technology behind modern music distribution and rights management — including ",
    leadBrand: "ANS Music",
    lead2: ", our white-label distribution platform used by labels to run their own branded business on 150+ streaming platforms.",
    primary: "Explore services",
    secondary: "Talk to us",
  },
  partners: "Platforms we deliver to",
  services: {
    kicker: "What we do",
    title: "A full technology stack for music & media",
    viewAll: "View all services",
    learnMore: "Learn more",
    indexTitle: "What we handle for you",
    indexSub:
      "From launching your own branded distribution platform to protecting your catalog across every major platform — here's the full picture of what ANS Digital handles for music and media businesses.",
    all: "All services",
    builtBy: (brand: string) => `Built by ${brand}, a brand of ANS Digital`,
    bestFor: "Best for",
    included: "What's included",
    interested: "Interested in this service?",
    interestedSub: "Tell us about your catalog and goals — we'll walk you through how it works.",
    getInTouch: "Get in touch",
    pricing: "Pricing",
    popular: "Most popular",
    audio: "Audio royalty",
    video: "Video royalty",
    pricingNote:
      "Pricing and revenue splits shown are for the ANS Music platform (currently in private beta) and may change during the beta period.",
    other: "Other services",
  },
  tools: {
    kicker: "Free tools",
    teaserTitle: "Shorten a link, right now",
    teaserSub: "Use the free tools we've built ourselves — starting with the link shortener below, with more on the way.",
    seeAll: "See all tools",
    indexTitle: "Free tools, built by us",
    indexSub:
      "Small utilities we've built for the music and media industry — starting with our link shortener, with more on the way for catalog and metadata work.",
    live: "Live",
    soon: "Coming soon",
    use: "Use tool",
    useNow: "Use it now",
  },
  why: { kicker: "Why ANS Digital", title: "Built in-house, end to end" },
  featured: {
    kicker: "Featured platform",
    title: "ANS Music — white-label distribution, built by us",
    body:
      "ANS Music is our flagship distribution platform: a fully white-label product that lets labels launch their own branded distribution business — custom domain, artist portal, and delivery to 150+ platforms — without building any of the underlying infrastructure themselves.",
    points: ["150+ streaming platforms, 24–48hr delivery", "Official VEVO video delivery on every plan", "Real-time royalty reporting and revenue splits"],
    cta: "See plans & pricing",
    tiles: [
      ["Unlimited artists", "on every plan"],
      ["VEVO delivery", "included, all tiers"],
      ["150+ platforms", "worldwide reach"],
      ["24–48hr", "average delivery"],
    ],
  },
  portfolio: {
    kicker: "Corporate structure",
    title: "One company, multiple brands",
    sub: "ANS Digital is the parent company. The brands and entities below are built and operated by us.",
    parent: "Parent company",
    operatedBy: "Operated by ANS Digital",
    visit: "Visit website",
  },
  cta: {
    title: "Ready to talk about your project?",
    sub: "Tell us what you're building — our team will help you find the right approach.",
    button: "Get in touch",
  },
  about: {
    kicker: "About us",
    title: "Media technology, built in-house",
    lead1: "ANS Digital is a technology company specializing in B2B/B2C music, media, and SaaS technology. We build and operate the products under our portfolio — including ",
    lead2: " — rather than reselling someone else's platform. We believe technology is not merely a service, it's a long-term business partnership.",
    vision: "Our vision",
    visionBody:
      "To shape the digital future of music and media, and establish ANS Digital as a reliable B2B technology partner offering services built to international standards.",
    mission: "Our mission",
    missionItems: [
      "Delivering dependable digital services to institutions of every size",
      "Developing modern, secure, and scalable technology solutions",
      "Enhancing our clients' capabilities while holding international standards",
      "Ensuring customer satisfaction and long-term partnerships",
      "Fostering technology-driven innovation in music and media",
    ],
    how: "How we work",
    steps: [
      ["Understand", "We start by understanding your catalog, your platforms, and what's actually slowing you down."],
      ["Set up", "We configure the right combination of platform, distribution, and protection services for your case."],
      ["Deliver", "Releases, claims, and reports move through automated, compliant pipelines — not manual spreadsheets."],
      ["Support", "Our technical team stays available for the issues that inevitably come up — we don't disappear after setup."],
    ],
    details: "Company details",
    license: "Trade License",
    address: "Registered address",
    email: "Email",
    compliance:
      "We operate in line with applicable regulatory and digital compliance requirements, prioritizing transparency, reliability, and professional technical support.",
  },
  faq: { kicker: "FAQ", title: "Frequently asked questions" },
  contact: {
    kicker: "Contact",
    title: "Get in touch",
    sub: "Tell us about your project or question — our team typically responds within one business day.",
    emailUs: "Email us",
    writeTo: "Write to",
    includeTitle: "What to include",
    include: ["Who you are and your label, company or channel", "Which service you're interested in", "Your catalog size and the platforms you work with", "Anything already slowing you down"],
    response: "Typical response time: one business day.",
  },
  footer: {
    desc: "Music & media technology: white-label distribution, rights management and the tools behind them.",
    brandNote: "ANS Music is a music-distribution brand built and operated by ANS Digital.",
    services: "Services",
    company: "Company",
    contact: "Contact",
    rights: "All rights reserved.",
    license: "Trade License",
    payments: "We accept",
  },
  a11y: { skip: "Skip to content", back: "Back to top" },
};

const bn: typeof en = {
  brand: "এএনএস ডিজিটাল",
  nav: { cta: "যোগাযোগ করুন", menu: "মেনু", lang: "English" },
  hero: {
    kicker: "মিউজিক ও মিডিয়া টেকনোলজি",
    title: "নির্ভরযোগ্য মিউজিক ও মিডিয়া টেকনোলজি সল্যুশন",
    lead1: "আমরা মিউজিক ডিস্ট্রিবিউশন ও রাইটস ম্যানেজমেন্টের প্রযুক্তি তৈরি করি — যার মধ্যে আছে ",
    leadBrand: "ANS Music",
    lead2: ", আমাদের হোয়াইট-লেবেল ডিস্ট্রিবিউশন প্ল্যাটফর্ম, যা দিয়ে লেবেলরা ১৫০+ স্ট্রিমিং প্ল্যাটফর্মে নিজস্ব ব্র্যান্ডে ব্যবসা চালায়।",
    primary: "সেবাসমূহ দেখুন",
    secondary: "যোগাযোগ করুন",
  },
  partners: "যেসব প্ল্যাটফর্মে আমরা কাজ করি",
  services: {
    kicker: "আমাদের সেবাসমূহ",
    title: "মিউজিক ও মিডিয়া প্রযুক্তির সম্পূর্ণ সমাধান",
    viewAll: "সব সেবা দেখুন",
    learnMore: "বিস্তারিত জানুন",
    indexTitle: "আমাদের সেবাসমূহ",
    indexSub: "মিউজিক ডিস্ট্রিবিউশন থেকে শুরু করে কপিরাইট প্রোটেকশন পর্যন্ত — আমরা আপনার প্রতিষ্ঠানের জন্য প্রয়োজনীয় সম্পূর্ণ প্রযুক্তি সমাধান প্রদান করি।",
    all: "সব সেবা",
    builtBy: (brand: string) => `${brand} দ্বারা নির্মিত, এএনএস ডিজিটাল-এর একটি ব্র্যান্ড`,
    bestFor: "যাদের জন্য",
    included: "যা যা থাকছে",
    interested: "এই সেবা নিয়ে আগ্রহী?",
    interestedSub: "আপনার ক্যাটালগ ও লক্ষ্য জানান — আমরা বুঝিয়ে দেব কীভাবে কাজ করে।",
    getInTouch: "যোগাযোগ করুন",
    pricing: "প্রাইসিং",
    popular: "সবচেয়ে জনপ্রিয়",
    audio: "অডিও রয়্যালটি",
    video: "ভিডিও রয়্যালটি",
    pricingNote: "এই প্রাইসিং ও রেভিনিউ শেয়ার ANS Music প্ল্যাটফর্মের (বর্তমানে প্রাইভেট বেটা) জন্য এবং বেটা চলাকালে পরিবর্তন হতে পারে।",
    other: "অন্য সেবাসমূহ",
  },
  tools: {
    kicker: "ফ্রি টুলস",
    teaserTitle: "লিংক শর্টেন করুন, এক্ষুনি",
    teaserSub: "আমাদের বানানো ফ্রি টুলস ব্যবহার করুন — নিচে শর্টনার দিয়ে শুরু, আরও টুলস শীঘ্রই আসছে।",
    seeAll: "সব টুলস দেখুন",
    indexTitle: "আমাদের তৈরি ফ্রি টুলস",
    indexSub: "মিউজিক ও মিডিয়া ইন্ডাস্ট্রির জন্য আমাদের বানানো ছোট ছোট টুলস — শুরু হচ্ছে আমাদের লিংক শর্টনার দিয়ে, ক্যাটালগ ও মেটাডেটা নিয়ে কাজ করার আরও টুলস আসছে।",
    live: "লাইভ",
    soon: "শীঘ্রই আসছে",
    use: "ব্যবহার করুন",
    useNow: "ব্যবহার করুন",
  },
  why: { kicker: "কেন এএনএস ডিজিটাল", title: "নিজেদের তৈরি প্রযুক্তি, শুরু থেকে শেষ" },
  featured: {
    kicker: "ফিচার্ড প্ল্যাটফর্ম",
    title: "ANS Music — আমাদের তৈরি হোয়াইট-লেবেল ডিস্ট্রিবিউশন",
    body: "ANS Music আমাদের প্রধান ডিস্ট্রিবিউশন প্ল্যাটফর্ম: একটি সম্পূর্ণ হোয়াইট-লেবেল প্রোডাক্ট, যা দিয়ে লেবেলরা নিজস্ব ব্র্যান্ডে ডিস্ট্রিবিউশন ব্যবসা চালু করতে পারে — কাস্টম ডোমেইন, আর্টিস্ট পোর্টাল, আর ১৫০+ প্ল্যাটফর্মে ডেলিভারি — কোনো ইনফ্রাস্ট্রাকচার নিজেদের বানাতে না হয়ে।",
    points: ["১৫০+ স্ট্রিমিং প্ল্যাটফর্ম, ২৪–৪৮ ঘণ্টায় ডেলিভারি", "প্রতিটি প্ল্যানে অফিসিয়াল VEVO ভিডিও ডেলিভারি", "রিয়েল-টাইম রয়্যালটি রিপোর্ট ও রেভিনিউ স্প্লিট"],
    cta: "প্ল্যান ও প্রাইসিং দেখুন",
    tiles: [
      ["আনলিমিটেড আর্টিস্ট", "প্রতিটি প্ল্যানে"],
      ["VEVO ডেলিভারি", "সব টিয়ারে অন্তর্ভুক্ত"],
      ["১৫০+ প্ল্যাটফর্ম", "বিশ্বব্যাপী"],
      ["২৪–৪৮ ঘণ্টা", "গড় ডেলিভারি"],
    ],
  },
  portfolio: {
    kicker: "কর্পোরেট স্ট্রাকচার",
    title: "একটি প্রতিষ্ঠান, একাধিক ব্র্যান্ড",
    sub: "এএনএস ডিজিটাল হলো প্যারেন্ট কোম্পানি — নিচের ব্র্যান্ড ও সত্তাগুলো আমরাই তৈরি ও পরিচালনা করি।",
    parent: "প্যারেন্ট কোম্পানি",
    operatedBy: "পরিচালনায়: এএনএস ডিজিটাল",
    visit: "ওয়েবসাইট দেখুন",
  },
  cta: {
    title: "আপনার প্রজেক্ট নিয়ে কথা বলতে চান?",
    sub: "আমাদের টিম আপনার প্রয়োজন বুঝে সঠিক সমাধান দিতে প্রস্তুত।",
    button: "যোগাযোগ করুন",
  },
  about: {
    kicker: "আমাদের সম্পর্কে",
    title: "এএনএস ডিজিটাল",
    lead1: "এএনএস ডিজিটাল একটি প্রযুক্তি প্রতিষ্ঠান, যারা B2B/B2C মিউজিক, মিডিয়া ও SaaS টেকনোলজিতে বিশেষজ্ঞ। আমরা আমাদের পোর্টফোলিও-এর প্রোডাক্টগুলো — যেমন ",
    lead2: " — নিজেরাই তৈরি ও পরিচালনা করি, অন্য কারো প্ল্যাটফর্ম resell করি না।",
    vision: "ভিশন",
    visionBody: "মিউজিক ও মিডিয়ার ডিজিটাল ভবিষ্যৎ গঠনে সক্রিয় ভূমিকা রাখা এবং আন্তর্জাতিক মানের সেবা প্রদানকারী একটি নির্ভরযোগ্য B2B প্রযুক্তি অংশীদার হিসেবে প্রতিষ্ঠিত হওয়া।",
    mission: "মিশন",
    missionItems: [
      "বিভিন্ন প্রতিষ্ঠানকে নির্ভরযোগ্য ডিজিটাল সেবা প্রদান",
      "আধুনিক, নিরাপদ ও স্কেলেবল প্রযুক্তি সমাধান তৈরি",
      "আন্তর্জাতিক মান বজায় রেখে ক্লায়েন্টদের সক্ষমতা বৃদ্ধি",
      "গ্রাহক সন্তুষ্টি ও দীর্ঘমেয়াদী অংশীদারিত্ব নিশ্চিতকরণ",
      "মিউজিক ও মিডিয়ায় প্রযুক্তি-চালিত উদ্ভাবনের প্রসার",
    ],
    how: "আমরা কীভাবে কাজ করি",
    steps: [
      ["বোঝা", "প্রথমে আমরা আপনার ক্যাটালগ, প্ল্যাটফর্ম আর আসলে কোথায় আটকে যাচ্ছেন, সেটা বুঝি।"],
      ["সেটআপ", "আপনার কেসের জন্য প্ল্যাটফর্ম, ডিস্ট্রিবিউশন ও প্রোটেকশন সেবার সঠিক সমন্বয় কনফিগার করি।"],
      ["ডেলিভারি", "রিলিজ, ক্লেইম ও রিপোর্ট চলে অটোমেটেড, কমপ্লায়েন্ট পাইপলাইনে — ম্যানুয়াল স্প্রেডশিটে নয়।"],
      ["সাপোর্ট", "যে সমস্যাগুলো অনিবার্যভাবে আসে, তার জন্য আমাদের টেকনিক্যাল টিম পাশে থাকে — সেটআপের পরে হারিয়ে যাই না।"],
    ],
    details: "প্রাতিষ্ঠানিক তথ্য",
    license: "ট্রেড লাইসেন্স",
    address: "নিবন্ধিত ঠিকানা",
    email: "ইমেইল",
    compliance: "আমরা প্রযোজ্য নিয়ম-নীতি ও ডিজিটাল কমপ্লায়েন্স মেনে স্বচ্ছতা, নির্ভরযোগ্যতা এবং পেশাদার টেকনিক্যাল সাপোর্টকে অগ্রাধিকার দিই।",
  },
  faq: { kicker: "প্রশ্নোত্তর", title: "সাধারণ জিজ্ঞাসা" },
  contact: {
    kicker: "যোগাযোগ",
    title: "যোগাযোগ করুন",
    sub: "আপনার প্রজেক্ট বা প্রশ্ন নিয়ে আমাদের সাথে যোগাযোগ করুন — আমরা সাধারণত এক কর্মদিবসের মধ্যে সাড়া দিই।",
    emailUs: "ইমেইল করুন",
    writeTo: "লিখুন",
    includeTitle: "ইমেইলে যা লিখবেন",
    include: ["আপনি কে, আপনার লেবেল, প্রতিষ্ঠান বা চ্যানেল", "কোন সেবায় আগ্রহী", "ক্যাটালগের আকার ও যেসব প্ল্যাটফর্মে কাজ করেন", "এখন কোথায় আটকে আছেন"],
    response: "সাধারণত এক কর্মদিবসের মধ্যে উত্তর দিই।",
  },
  footer: {
    desc: "মিউজিক ও মিডিয়া টেকনোলজি: হোয়াইট-লেবেল ডিস্ট্রিবিউশন, রাইটস ম্যানেজমেন্ট ও এর পেছনের টুলস।",
    brandNote: "ANS Music, এএনএস ডিজিটাল-এর একটি মিউজিক ডিস্ট্রিবিউশন ব্র্যান্ড।",
    services: "সেবাসমূহ",
    company: "প্রতিষ্ঠান",
    contact: "যোগাযোগ",
    rights: "সর্বস্বত্ব সংরক্ষিত।",
    license: "ট্রেড লাইসেন্স",
    payments: "পেমেন্ট গ্রহণ",
  },
  a11y: { skip: "মূল কনটেন্টে যান", back: "উপরে যান" },
};

export const COPY: Record<Locale, typeof en> = { en, bn };

export const LOCALES: Locale[] = ["en", "bn"];

export function base(locale: Locale) {
  return `/${locale}`;
}
